image: Ubuntu1804
stack: node 16
branches:
  only:
  - main
cache: node_modules
install:
  - npm install
  - npm ci
  - npx puppeteer install
before_test:
  - npm run start &
test_script:
  - npx wait-on http://localhost:9000 && npm test
build: off
test_script: 
  - npm run lint
  - npm test
  - npm run e2e